FROM @jessie-base-image@
MAINTAINER @maintainer@

# Use a locally downloaded Xilinx installer archive
ADD Xilinx_Vivado_SDK_Lin_2015.4_1118_2.tar.gz /tmp/
# Xilinx recommends recreating this config file for every release
COPY xsetup_config_2015.4.txt 	/tmp/
# Get the avnet board definition files also
ADD http://zedboard.org/sites/default/files/documentations/Avnet%20Zed%20Board%20Definitions%202015_3or4_160331_2.zip /tmp/

# Extract the archive so we can get to the contents
RUN cd /tmp/Xilinx_Vivado_SDK_Lin_2015.4_1118_2 && \
    sed -i -- 's/uname -i/uname -m/' xsetup && \
    sudo ./xsetup --batch Install \
    --agree XilinxEULA,3rdPartyEULA,WebTalkTerms \
    -c /tmp/xsetup_config_2015.4.txt && \
    cd /tmp && \
    sudo chown -R developer:developer /opt && \
    sudo chown -R developer:developer /tmp && \
    unzip "Avnet Zed Board Definitions 2015_3or4_160331_2.zip" -d avboards && \
    cd /tmp/avboards && \
    unzip "Avnet Zed Boards 2015_3or4_160331.zip" \
    -d /opt/Xilinx/Vivado/2015.4/data/boards/board_files/ && \
    cd / && \
    rm -rf /tmp/*

# Install the license file
COPY Xilinx.lic /opt/Xilinx
ENV XILINXD_LICENSE_FILE /opt/Xilinx
